jenkins:
  systemMessage: "Jenkins configured automatically by Configuration as Code plugin"
  numExecutors: 2
  mode: NORMAL
  
  securityRealm: "none"
  authorizationStrategy: "unsecured"

  globalNodeProperties:
    - envVars:
        env:
          - key: "DOCKER_HOST"
            value: "unix:///var/run/docker.sock"

jobs:
  - script: |
      job('seed-job') {
        description('Seed job to create all other jobs')
        scm {
          git {
            remote {
              url('.')
            }
            branch('*/main')
          }
        }
        triggers {
          scm('H/5 * * * *')
        }
        steps {
          dsl {
            external('jenkins/jobs/*.groovy')
            removeAction('DELETE')
          }
        }
      }

tool:
  nodejs:
    installations:
      - name: "NodeJS-18"
        properties:
          - installSource:
              installers:
                - nodeJSInstaller:
                    id: "18.17.0"
                    npmPackagesRefreshHours: 72