jenkins:
  systemMessage: "Jenkins configured automatically by Configuration as Code plugin"
  numExecutors: 2
  mode: NORMAL
  securityRealm:
    local:
      allowsSignup: false
      users:
       - id: admin
         password: admin123
         name: "Admin User"
         properties:
          - mailer:
              emailAddress: 
  authorizationStrategy:
    unsecured: {}
    # Alternativa más permisiva pero con algo de control:
    # globalMatrix:
    #   permissions:
    #     - "Overall/Administer:admin"
    #     - "Overall/Read:anonymous"
    #     - "Job/Build:anonymous"
    #     - "Job/Cancel:anonymous"
    #     - "Job/Configure:anonymous"
    #     - "Job/Create:anonymous"
    #     - "Job/Delete:anonymous"
    #     - "Job/Discover:anonymous"
    #     - "Job/Read:anonymous"
    #     - "Job/Workspace:anonymous"

  globalNodeProperties:
    - envVars:
        env:
          - key: "DOCKER_HOST"
            value: "unix:///var/run/docker.sock"

security:
  scriptApproval:
    approvedScriptHashes: []
    approvedSignatures: []
    approvedClasspathEntries: []
    pendingScripts: []
  # Deshabilitar la aprobación de scripts para automatización
  globalJobDslSecurityConfiguration:
    useScriptSecurity: false

jobs:
  - script: |
      job('seed-job') {
        description('Seed job to create all other jobs')
        scm {
          git {
            remote {
              url('https://github.com/SantiagoH31/fullstack-docker.git')
            }
            branch('*/main')
          }
        }
        triggers {
          scm('H/5 * * * *')
        }
        steps {
          dsl {
            external('jenkins/jobs/*.groovy')
            removeAction('DELETE')
          }
        }
      }

tool:
  nodejs:
    installations:
      - name: "NodeJS-18"
        properties:
          - installSource:
              installers:
                - nodeJSInstaller:
                    id: "18.17.0"
                    npmPackagesRefreshHours: 72